### ISSUE TITLE
Bulk Similarity Search

### ISSUE THREAD

**Issue by totalhack** [qdrant/qdrant_client#106]
I'd like a way to do bulk similarity search so I can more efficiently query to see if a set of embeddings either already exists or already has a similar match greater than some threshold. I think if the search API supported querying for multiple embeddings it would allow me to build any other needed logic on top easily. It could just return multiple results back in the same order as the input query embeddings. Is something like this already doable? Thanks.

**Comment by kacperlukawski** [comment]
Hi, do you mean batch search? It's already built-in: https://qdrant.tech/documentation/search/#batch-search-api

**Comment by totalhack** [comment]
Yup, that looks like exactly what I need. Sorry I missed it in the docs. Thanks for your help.
