### ISSUE TITLE
Cannot connect to Qdrant cloud instance

### ISSUE THREAD

**Issue by dylanjcastillo** [qdrant/qdrant_client#107]
### Overview

I'm unable to connect to a Qdrant instance, even though I'm following the instructions provided in the documentation.

### Steps to reproduce

1. Launch qdrant instance
2. Create environment variables with host and API key
3. Run the following code:

  ```python
  import os
  
  from qdrant_client import QdrantClient
  from qdrant_client.http import models
  
  host_name = os.getenv("QDRANT_HOST")
  api_key = os.getenv("QDRANT_API_KEY")
  
  client = QdrantClient(
      host=host_name, api_key=api_key
  )
  
  client.recreate_collection(
      collection_name="test-collection",
      vectors_config=models.VectorParams(size=100, distance=models.Distance.COSINE),
  )
  ```

### Observed Behavior

The code fails to run, and raises the following exception: `ResponseHandlingException: 502 Bad Gateway`. It also fails if I replace `https` by `http` or set `prefer_grpc=True`.

### Expected Behavior

Connection is successful and I'm able to create a collection.

### Notes

I installed `qdrant-client` using poetry and I'm suing a Mac with an M1 processor, and OS 13.2.

**Comment by kacperlukawski** [comment]
@dylanjcastillo Does the value of `QDRANT_HOST` include the protocol as well? I mean "https://"

**Comment by dylanjcastillo** [comment]
Yes, it looks like this:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/7218756/218469120-2120c5b0-3965-45a4-ab63-dd0bfef7ab28.png">

**Comment by dylanjcastillo** [comment]
It works well if I run it locally using Docker.

**Comment by kacperlukawski** [comment]
@dylanjcastillo Could you please try putting just a hostname in `QDRANT_HOST`? Please just remove the protocol and try again. Or, if you're using the latest version of the qdrant-client, you can use a different parameter:

```
host_name = os.getenv("QDRANT_HOST")
api_key = os.getenv("QDRANT_API_KEY")

client = QdrantClient(
    url=host_name, api_key=api_key
)
```

It was sometimes confusing, so we decided to change the parameters: https://github.com/qdrant/qdrant_client/pull/99

**Comment by dylanjcastillo** [comment]
Ah, you're right! It works now. I copied the URL from the `Cluster URL` section, and didn't realize the `https://` was missing from the examples.
