### ISSUE TITLE
`.upload_collection()` does not work with named vectors

### ISSUE THREAD

**Issue by monatis** [qdrant/qdrant_client#114]
For the initial upload, `QdrantClient.upload_collection()` should also work with named vectors, just as `.upload_records()`. A union over the current possible types and their dictionary counterparts should be implemented.

**Comment by HridayM25** [comment]
Hi @monatis, can I give a shot to this if it hasn't been taken yet?

**Comment by monatis** [comment]
Hi @HridayM25, this was already implemented in #121. You can have a look at #113 or others you may like, or suggest your own improvements.

**Comment by HridayM25** [comment]
Hi, thanks for the response.
I'll look over what you have mentioned and try to look for improvements.
