### ISSUE TITLE
Error when not specifying arguments in upload_collection

### ISSUE THREAD

**Issue by Uzay-G** [qdrant/qdrant_client#36]
I get `TypeError: upload_collection() missing 2 required positional arguments: 'payload' and 'ids'` when I do:

```python
client.upload_collection(
    collection_name="personal_test",
    vectors=embs
)
```
Aren't these arguments optional?

**Comment by generall** [comment]
Yes, they are optional. You can provide `None` as a placeholder. Agreed, that it would be better to provide None as default values as well.

**Comment by generall** [comment]
Fixed in https://github.com/qdrant/qdrant_client/releases/tag/v0.8.0
