### ISSUE TITLE
Not able to install qdrant client

### ISSUE THREAD

**Issue by vishu1994** [qdrant/qdrant_client#4]
Command : pip install qdrant-client

ERROR: Could not find a version that satisfies the requirement qdrant-client (from versions: none)
ERROR: No matching distribution found for qdrant-client

**Comment by generall** [comment]
Hi, can you pls provide more information about your environment? What python version do you use?

**Comment by vishu1994** [comment]
@generall  I upgraded the python version fropm 3.6 to 3.7 now it works.
