### ISSUE TITLE
Python Client search docs

### ISSUE THREAD

**Issue by GeorgePearse** [qdrant/qdrant_client#42]
No (obviously) docs for the search by ID function for the python client, worth just having in the full example. Happy to add if they genuinely don't exist if someone can point me to the original code. + happy to implement if the code doesn't exist if someone can point me in the right direction.

**Comment by imneonizer** [comment]
I have atleast 100 detected objects and for each one I need to search matching embeddings, HTTP was very slow for now I am using grpc and the elapsed time is around `100ms` with qdrant server running locally.
````python
client.search(
  collection_name=collection_name,
  query_vector=embedding,
  query_filter=None,
  append_payload=True,
  limit=1,
)
````

If I could batch search multiple embeddings at once that would save lot of time.

**Comment by generall** [comment]
Hi @imneonizer, the batch search method will be available with next qdrant release, it is already merged in master branch - https://github.com/qdrant/qdrant/issues/186
