### ISSUE TITLE
Add new points to an existing collection

### ISSUE THREAD

**Issue by fadi212** [qdrant/qdrant_client#46]
I created a collection and added some points to it and I was able to search through that collection but when I am trying to add more points to an existing collection, that is not working.

My code:
`qd_client.upload_collection(
      collection_name='startups',
      vectors=vectors1,
      payload=payload1,
      ids=ids1,
      batch_size=256 
  )
`

Now when I am trying to add more points,
`qd_client.upload_collection(
      collection_name='startups',
      vectors=vectors2,
      payload=payload2,
      ids=ids2,
      batch_size=256
  )`

It is not working. can you please guide here quickly @generall @monatis

**Comment by generall** [comment]
Hi @fadi212! Can you please elaborate on the issue? Are there any errors in client/service logs?

**Comment by sainivedh19pt** [comment]
@fadi212 Hi, In the Qdrant_Client class theres a upsert method to add new points. Maybe you could give it a try

Thanks

**Comment by imneonizer** [comment]
I am trying to achieve the same, here is a quick reproducible code

````python
# create random data
np.random.seed(0)
embeddings = np.array([np.random.rand(64) for i in range(100)])
labels = [{"label": str(i)} for i in range(100)]
````

- This works
````python
client.upload_collection(
    collection_name="test",
    vectors=embeddings,
    payload=labels,
    parallel=2
)

# uploading all the embeddings at once
res = client.search(
        collection_name="test",
        query_vector=embeddings[0],
        query_filter=None,
        append_payload=True,
        limit=1
    )

print(res[0].payload["label"])

# output is 0, since labels are basically index of each embedding
````


- This doesn't works
````python
# upload first 50 items
client.upload_collection(
    collection_name="test",
    vectors=embeddings[:50],
    payload=labels[:50],
    parallel=2
)

# upload remaining items
client.upload_collection(
    collection_name="test",
    vectors=embeddings[50:],
    payload=labels[50:],
    parallel=2
)

res = client.search(
        collection_name="test",
        query_vector=embeddings[0],
        query_filter=None,
        append_payload=True,
        limit=1
    )

print(res[0].payload["label"])

# output is 94, which is incorrect
````

I read about `upsert` method but I am not able to update the collections as per the requirement I have shown in the above example. It will be very helpful If someone can share snippets to update the collection.

**Comment by generall** [comment]
> 
```# upload remaining items
client.upload_collection(
    collection_name="test",
    vectors=embeddings[50:],
    payload=labels[50:],
    parallel=2
)
```

This doesn't work because ids are not specified. `upload_collection` can auto-generate Ids, but it starts with 0.
