### ISSUE TITLE
Have a batch upload to collection method

### ISSUE THREAD

**Issue by wammy19** [qdrant/qdrant_client#6]
Feature request here.

I currently have a use case where I'm batching together documents for encoding so that I can saturate the GPU and speed up the encoding step. But then I'm having to loop over all the documents and upload them individually one by one. It would be nice to just pass a list of documents into a method and have them be indexed all at once similar to recreate_collection() for an initial creation of a collection.

**Comment by generall** [comment]
Hi, sorry for late response;) there are batch upload capabilities in https://qdrant.github.io/qdrant/redoc/index.html#operation/upsert_points endpoint. and here is an example of how to use it https://github.com/qdrant/qdrant_client/blob/0b499b0fd5244175aeb948f913e3b81fc0beae61/tests/test_qdrant_client.py#L142
