### ISSUE TITLE
Needs timeout setting

### ISSUE THREAD

**Issue by ncoder** [qdrant/qdrant_client#84]
I see some api calls have timeouts as an argument... but not all. This probably needs a more general pattern of timeout handling.

I'm getting timeouts on "create_snapshot". Listing the shapshots after handling the exception shows the request was successful.

related to #79

**Comment by generall** [comment]
Hi @ncoder! I made a PR to address the issue - https://github.com/qdrant/qdrant_client/issues/84

Would you mind to review it?

**Comment by ncoder** [comment]
With pleasure. Done. Looks godo.

**Comment by manny-uncharted** [comment]
I noticed that there are some issues that have already been resolved yet they are still left open. like this one @ncoder
