### ISSUE TITLE
Providing a hostname that contains `https://` causes connection error

### ISSUE THREAD

**Issue by nleroy917** [qdrant/qdrant_client#88]
### Overview
I was using the qdrant client to connect to a qdrant instance hosted on qdrant cloud. When I provided `QdrantClient` with my hostname that contained `https://` I noticed that it refused to connect as it couldn't find the host. Removing `https://` solves the problem.

### Steps to reproduce:
1. Launch qdrant instance on qdrant cloud:
2. Set env variables:
```
export QDRANT_HOST="https://my-hostname.qdrant.io"
export QDRANT_PORT=6333
export QDRANT_API_KEY=my-api-key
```
3. Attempt connection to qdrant and pull information:
```python
import os
from qdrant_client import QdrantClient

qdrant = QdrantClient(
  host=os.environ.get("QDRANT_HOST"),
  port=os.environ.get("QDRANT_PORT"),
  api_key=os.environ.get("QDRANT_API_KEY")
)
collection_info = qdrant.get_collection("my-collection")
```
### Observed Behavior:
Error received:
```
ResponseHandlingException
[Errno 8] nodename nor servname provided, or not known
```

### Expected Behavior:
I would expect `QdrantClient` to successfully connect to a host regardless if it was prefixed with `https://` or not.

### Notes
I was able to figure out that removing `https://` would resolve the issue by inspecting the code. I [see](https://github.com/qdrant/qdrant_client/blob/9b64ada9f569c9f46e2c9d8eea74d683716f9a6a/qdrant_client/qdrant_client.py#L106) it's building up the scheme based on parameters. It'd be nice if it sanitized the URI prior to this, or at least warned a user that they have `http` in their host.

**Comment by generall** [comment]
Hi @nleroy917, in URL, the host name does not contain the schema by definition.
But I would agree, that it might be better to accept full URL, rather than just a host name

**Comment by nleroy917** [comment]
Hi @generall, thanks for the reply. I had started on a PR but got tripped up on some things in the development guide. Namely, the generation of the REST code: `bash -x tools/generate_rest_client.sh`.

I can try again.

**Comment by generall** [comment]
Fixed in https://github.com/qdrant/qdrant_client/pull/99
