### ISSUE TITLE
How to find bottom values

### ISSUE THREAD

**Issue by ahmadmustafaanis** [qdrant/qdrant_client#9]
In search, we can do 
```python3
qdrant_client.search(
            collection_name=self.collection_name,
            query_vector=vector[0],
            query_filter=None, 
            top=5,  # 5 the most closest results is enough
        )
```
How can we do
```python3
qdrant_client.search(
            collection_name=self.collection_name,
            query_vector=vector[0],
            query_filter=None,  # We don't want any filters for now
            bot=5,  # 5 the most farthest results 
        )
```
Like I want the 5 results which are least similar. I do not want to fetch all the results, and take the last 5 from the list. Is there any better way?

**Comment by generall** [comment]
Hi @ahmadmustafaanis thanks for the question! Currently there is no way to request least similar vector directly. This type of query would require completely different index, incompatible with regular most-similar search.

What you can do instead is to search for **inverted** vector. The actual insertion operation depends on your vector types, I would suggest to try `neg_vector = 1 - query_vector` or `neg_vector = -query_vector`. I would love to hear from your experiments if it worked or not!

Also this type of issues looks more suitable for https://github.com/qdrant/qdrant repository, cause it is not directly related to python client.

**Comment by generall** [comment]
@ahmadmustafaanis is you problem solved?

**Comment by ahmadmustafaanis** [comment]
Yeah. I was thinking from the wrong perspective.
