### ISSUE TITLE
Automatically get host and port from an environment variable

### ISSUE THREAD

**Issue by ChickenTarm** [qdrant/qdrant_client#92]
It would be useful to be able to do
```python
qc.QdrantClient()
```
where the client will check if there the environment variables "QDRANT_IP, QDRANT_PORT, QDRANT_GRPC_PORT" present and if so will use those value.

**Comment by generall** [comment]
Closed in favor of url param, please consider using

```
qc.QdrantClient(url=os.getenv("QDRANT_URL"))
```
