### ISSUE TITLE
Mandatory parameter "port" for client initialization

### ISSUE THREAD

**Issue by ThomasKLY** [qdrant/qdrant_client#96]
# Overview
I was trying setup the client to connect to a host without specifying a port, but the URI is parsed incorrectly.

# Description
The URI I was trying to enter looks like this:
`https://vector_store.com`

I tried to initialize the client using `None` as the parameter for `port`:
```python
client = QdrantClient(host="vector_store.com", https=True, port=None)
```
But it didn't work cause the REST URI is incorrectly parsed:
```python
client.rest_uri == "https://vector_store.com:None"
```

# Proposed solution
Modify [the URI generation logic](https://github.com/qdrant/qdrant_client/blob/58fa65156e0f84d651835f6b1fa56471edf7e039/qdrant_client/qdrant_client.py#L105) to handle an empty port.

```python
# Original
self.rest_uri = f"http{'s' if self._https else ''}://{host}:{port}{self._prefix if self._prefix is not None else ''}"

# Proposed modification
self.rest_uri = f"http{'s' if self._https else ''}://{host}{':' + str(port) if port is not None else ""}{self._prefix if self._prefix is not None else ''}"
```

**Comment by generall** [comment]
Hi @ThomasKLY! Thanks for the suggestion, I think it might be really useful! You can make a PR yourself, or we will shortly

**Comment by ThomasKLY** [comment]
Thanks for the fix, that was really quick!
