### ISSUE TITLE
Batch gives validation errors for `payloads`

### ISSUE THREAD

**Issue by GoodluckH** [qdrant/qdrant_client#98]
```py
qdrant_client.upsert(
    collection_name=collection_name,
    points=Batch(
        ids=[1],
        vectors=[dummy_embed(doc) for doc in docs],
        payloads=[{"good": "yes", "hello": "world"}]
    ),
)
```

See the above, when I ran the above, I get this error:
```
{\"result\":null,\"status\":{\"error\":\"Json deserialize error: invalid type: map, expected a sequence at line 1 column 7730\"},\"time\":0.0}
```

Not really sure how what it means. I checked the source code, it seems like an array of maps is expected for `payloads` field.

Weirdly enough, if I change `payloads` to having a map of only one key-value pair, I would get a different error from FastAPI.

```py
payloads=[{"good": "yes"}]
```

Error:
```
 validation error for Batch\npayloads\n  value is not a valid dict (type=type_error.dict)
```

**Comment by generall** [comment]
Is the docs size = 1 in your example?

**Comment by GoodluckH** [comment]
> Is the docs size = 1 in your example?

Yes. 

I got it to work by not using Batch:
```py
qdrant_client.upsert(
        collection_name=collection_name,
        points=[
            PointStruct(id=uuid.uuid4().hex,
            vector=embeddings[i],
            payload={"page_content": doc, "metadata": metadatas[i]}) for i, doc in enumerate(docs)
        ]
    )
```

**Comment by generall** [comment]
This request looks different. Can you please share what was the `dummy_embed` doing? I tried to reproduce your problem with

```
    client.upsert(
        collection_name=COLLECTION_NAME,
        points=Batch(
            ids=[3],
            vectors=[np.random.rand(DIM).tolist()],
            payload=[{"test": "value", "test2": "value2"}],
        )
    )
```

but it works for me

**Comment by GoodluckH** [comment]
The dummy_embed just create a random vector. That's fine without `payloads`, but as soon as I have `payloads`, the type error appears.

**Comment by jflam** [comment]
I'm seeing this too. The annotations look OK as well in my local copy of `qdrant_client`:

```
models:31
class Batch(BaseModel):
    ids: List["ExtendedPointId"] = Field(..., description="")
    vectors: "BatchVectorStruct" = Field(..., description="")
    payloads: Optional[List["Payload"]] = Field(None, description="")

models:788
Payload = Dict[Any, Any]
```

The langchain wrapper is written to use Batch, which is how I ran into this. 


<img width="622" alt="image" src="https://user-images.githubusercontent.com/8877/216804245-d43c5cbe-48f4-47ef-96a9-ac0af4147383.png">

**Comment by generall** [comment]
Hi @jflam! Could you please share the exact values of values of `payloads` which gives you an error? I can't really reproduce it :disappointed:

**Comment by jflam** [comment]
This errors with .10 but runs fine in .9. As I said above, `Payload=Dict[Any,Any]` is what's triggering the issue. If you change it back to `Payload=dict` it runs fine.

```
client.upsert(collection_name="test", wait=True, points=rest.Batch(
    ids=[2,3], 
    vectors=[e1,e1], 
    payloads=[
       {"a": "b",}, 
       {"a": "b",}
    ]))
```

**Comment by joein** [comment]
Simple example to reproduce the error:

```Python
OkDict = Dict[Any, Any]


class DebugModel(BaseModel):
    ok_values: List["OkDict"] = Field(..., description="")
    not_ok_values: List["NotOkDict"] = Field(..., description="")


NotOkDict = Dict[Any, Any]
DebugModel.update_forward_refs()

print(DebugModel(
    ok_values=[{"key1": "value1", "key2": "value2"}],
    not_ok_values=[{"key1": "value1", "key2": "value2"}]
))
```

Output:
```Python
ok_values=[{'key1': 'value1', 'key2': 'value2'}] not_ok_values={'key1': 'key2'}
```

**Comment by joein** [comment]
@GoodluckH @jflam could you check if the issue still happens for you in 1.0.0 ?
